# Generated by Django 4.0.5 on 2022-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_account_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
