# Generated by Django 4.0.5 on 2022-09-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_user_delete_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
